CREATE SEQUENCE invisible_users_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE online_users_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE queries_id_seq1 START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE requests_id_seq1 START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE shout_revisions_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE shout_smilies_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE shout_words_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE smilies_id_seq1 START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE user_categories_id_seq1 START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE words_id_seq1 START WITH 1 INCREMENT BY 50;
CREATE TABLE invisible_users (id INTEGER NOT NULL, timestamp TIMESTAMP, users INTEGER, PRIMARY KEY (id));
CREATE TABLE online_users (id INTEGER NOT NULL, timestamp TIMESTAMP, user_id INTEGER, PRIMARY KEY (id));
CREATE TABLE queries (id INTEGER NOT NULL, date TIMESTAMP, execution_time DOUBLE, parameters CLOB, query CLOB, request INTEGER NOT NULL, PRIMARY KEY (id));
CREATE TABLE requests (id INTEGER NOT NULL, browser VARCHAR(255), timestamp TIMESTAMP, ip CLOB, request_time DOUBLE, url CLOB, username VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE settings (key VARCHAR(255) NOT NULL, value CLOB, PRIMARY KEY (key));
CREATE TABLE shouts (primary_id INTEGER NOT NULL, date TIMESTAMP, day INTEGER, deleted INTEGER, epoch INTEGER, hour INTEGER, id INTEGER, message CLOB, month INTEGER, year INTEGER, user_id INTEGER, PRIMARY KEY (primary_id), CONSTRAINT U_SHOUTS_ID UNIQUE (id, epoch));
CREATE TABLE shout_revisions (id INTEGER NOT NULL, date TIMESTAMP, replaced TIMESTAMP, revision INTEGER, text CLOB, user_id INTEGER, shout INTEGER, PRIMARY KEY (id), CONSTRAINT U_SHT_SNS_SHOUT UNIQUE (shout, revision));
CREATE TABLE shout_smilies (id INTEGER NOT NULL, count INTEGER NOT NULL, shout INTEGER, smiley INTEGER, PRIMARY KEY (id), CONSTRAINT U_SHT_MLS_SHOUT UNIQUE (shout, smiley));
CREATE TABLE shout_words (id INTEGER NOT NULL, count INTEGER NOT NULL, shout INTEGER, word INTEGER, PRIMARY KEY (id), CONSTRAINT U_SHT_RDS_SHOUT UNIQUE (shout, word));
CREATE TABLE smilies (id INTEGER NOT NULL, code VARCHAR(255), filename VARCHAR(255), meaning CLOB, PRIMARY KEY (id), CONSTRAINT U_SMILIES_CODE UNIQUE (code));
CREATE TABLE users (id INTEGER NOT NULL, name CLOB, category INTEGER, PRIMARY KEY (id));
CREATE TABLE user_categories (id INTEGER NOT NULL, color CLOB, name CLOB, PRIMARY KEY (id));
CREATE TABLE user_credentials (id INTEGER NOT NULL, access_token CLOB, cookie CLOB, password CLOB, securitytoken CLOB, PRIMARY KEY (id));
CREATE TABLE words (id INTEGER NOT NULL, word VARCHAR(255), PRIMARY KEY (id));
ALTER TABLE online_users ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE queries ADD FOREIGN KEY (request) REFERENCES requests (id);
ALTER TABLE shouts ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE shout_revisions ADD FOREIGN KEY (shout) REFERENCES shouts (primary_id);
ALTER TABLE shout_smilies ADD FOREIGN KEY (shout) REFERENCES shouts (primary_id);
ALTER TABLE shout_smilies ADD FOREIGN KEY (smiley) REFERENCES smilies (id);
ALTER TABLE shout_words ADD FOREIGN KEY (shout) REFERENCES shouts (primary_id);
ALTER TABLE shout_words ADD FOREIGN KEY (word) REFERENCES words (id);
ALTER TABLE users ADD FOREIGN KEY (category) REFERENCES user_categories (id);
ALTER TABLE user_credentials ADD FOREIGN KEY (id) REFERENCES users (id);